import type { EdgeCase } from "@/lib/types";

const e = (category: string, slug: string, title: string, why: string, bug: string, mitigation: string, projects: string[]): EdgeCase => ({ category, slug, title, why, bug, mitigation, projects });

export const edgeCases: EdgeCase[] = [
  e("Payments", "webhook-before-response", "Webhook arrives before checkout response", "Provider processing and webhook delivery race the client request.", "A monotonic client flow rejects a valid success or emits two receipts.", "Treat webhook and response as facts applied to one state machine; dedupe provider event and stable payment reference.", ["ecommerce", "payment-platform"]),
  e("Payments", "success-after-timeout", "Payment succeeds after caller timeout", "The remote side committed before the network failed.", "Retry creates a duplicate charge or order remains falsely failed.", "Use a stable provider idempotency reference, pending state, retrieval, and reconciliation.", ["ecommerce", "payment-platform"]),
  e("Payments", "partial-refund-race", "Concurrent partial refunds exceed capture", "Two workers calculate refundable amount from the same snapshot.", "Total refunded exceeds the captured amount.", "Lock the aggregate or atomically decrement available refundable amount; include pending refunds.", ["payment-platform"]),
  e("Booking", "last-slot-race", "Two users confirm the last slot", "Availability reads are snapshots, not reservations.", "Both users receive confirmation.", "Enforce capacity with a transaction, range exclusion, or unique constraint at confirmation.", ["appointment-saas", "hotel-pms"]),
  e("Booking", "hold-expires-in-payment", "Reservation hold expires during payment", "External authorization outlives the local hold.", "Money is taken without inventory.", "Bound the hold, keep an explicit pending state, and void/refund late success through reconciliation.", ["appointment-saas", "ecommerce"]),
  e("Booking", "business-date-midnight", "Operational day differs from calendar day", "Night work crosses midnight and properties use a controlled business date.", "Charges land on the wrong report or run twice.", "Store business_date explicitly and make closing idempotent per tenant/date.", ["hotel-pms"]),
  e("Authentication", "revoked-session-cache", "Revoked membership survives a cache", "Authorization cache has not observed the revocation.", "A removed user reads tenant data.", "Use short TTL plus membership epoch/invalidation and reauthorize sensitive object reads.", ["project-management", "cloud-file-storage"]),
  e("Authentication", "account-enumeration", "Recovery reveals whether an account exists", "Different status, timing, or email behavior leaks identity.", "Attackers enumerate users.", "Return uniform responses, rate-limit, and monitor recovery abuse while still notifying the real owner.", ["social-network"]),
  e("Authentication", "signed-link-forwarded", "Capability link is forwarded", "Anyone holding the URL may exercise its scope.", "Unintended recipient edits or downloads data.", "Use least scope, short expiry, revocation, optional recipient verification, and never embed excess data.", ["appointment-saas", "cloud-file-storage"]),
  e("File Upload", "bytes-without-metadata", "Upload completes but metadata does not", "Direct object upload and metadata commit are separate.", "Orphaned bytes consume quota forever.", "Use staging prefixes/session expiry and a reconciler that removes unclaimed objects.", ["cloud-file-storage", "video-streaming"]),
  e("File Upload", "metadata-without-bytes", "Metadata points at a missing object", "The app trusted the client or object operation failed.", "Downloads fail after a claimed successful upload.", "Verify server-side size/checksum before publish and keep new versions quarantined.", ["cloud-file-storage", "video-streaming"]),
  e("File Upload", "archive-bomb", "Archive expands beyond limits", "Compressed size does not bound extracted bytes or file count.", "Scanner exhausts disk, memory, or CPU.", "Sandbox extraction with byte/file/depth/time limits and reject path traversal.", ["cloud-file-storage"]),
  e("Realtime", "out-of-order-location", "Location batches arrive out of order", "Mobile networks buffer and retry old samples.", "A courier or driver appears to move backward.", "Use device sequence and sample time; only newer samples update live state.", ["food-delivery", "ride-hailing"]),
  e("Realtime", "revoked-socket", "Revoked user keeps a live subscription", "Socket authentication predates a membership change.", "Private changes continue to stream.", "Push revocation, expire session epochs, and reauthorize channel delivery.", ["project-management"]),
  e("Realtime", "presence-is-not-authority", "Presence says offline while user is active", "Heartbeats are lossy and gateways partition.", "Workflow incorrectly cancels or reassigns work.", "Treat presence as a hint; make durable transitions explicit and show freshness.", ["ride-hailing", "project-management"]),
  e("Messaging", "event-delivered-twice", "Worker processes an event twice", "At-least-once brokers redeliver after lost acknowledgements.", "Email, payout, or task is duplicated.", "Use consumer inbox/unique business key and make side effects idempotent.", ["ecommerce", "food-delivery", "payment-platform"]),
  e("Messaging", "poison-message", "One message always crashes a worker", "Payload is invalid or triggers a deterministic bug.", "Queue stalls or retries forever.", "Bound attempts, dead-letter with diagnostics, alert, and support replay after correction.", ["video-streaming", "payment-platform"]),
  e("Messaging", "event-schema-drift", "Producer deploys an incompatible event", "Consumers upgrade independently.", "Old consumers misread or discard data.", "Use additive versioned schemas, compatibility tests, and tolerant readers; never repurpose fields.", ["project-management", "social-network"]),
  e("Notifications", "reminder-after-reschedule", "Old reminder fires after reschedule", "A scheduled job captured an earlier appointment version.", "Customer arrives at the wrong time.", "Job checks current version/status immediately before send and uses unique appointment/version key.", ["appointment-saas"]),
  e("Notifications", "notification-fanout-spike", "Popular action creates millions of notifications", "Recipient fan-out is highly skewed.", "Queue delay impacts unrelated transactional messages.", "Separate queues/priorities, cap or aggregate social notifications, and apply backpressure.", ["social-network"]),
  e("Inventory", "oversell-on-read", "Availability read causes oversell", "Two buyers see the same available count.", "Reservations exceed on-hand stock.", "Lock/update invariant at reservation time; do not trust cache or earlier read.", ["ecommerce"]),
  e("Inventory", "reservation-leak", "Expired reservation never releases", "A process dies before cleanup.", "Stock appears permanently unavailable.", "Store expiry/status durably; indexed reaper conditionally releases active holds.", ["ecommerce"]),
  e("Inventory", "menu-version-drift", "Menu changes between browse and order", "Restaurant availability and price are volatile.", "Wrong item or price is ordered.", "Bind quote to menu version and return an explicit change diff during revalidation.", ["food-delivery"]),
  e("Multi-tenancy", "cache-key-misses-tenant", "Cache key omits tenant id", "Two tenants use the same object id or natural key.", "One tenant receives another's data.", "Include tenant and authorization/version dimensions in every shared cache key; test collisions.", ["hotel-pms", "appointment-saas", "project-management"]),
  e("Multi-tenancy", "cross-tenant-foreign-key", "Row references another tenant", "Schema checks only object id, not tenant ownership.", "Queries or cascades cross the isolation boundary.", "Use composite tenant foreign keys and derive tenant from authenticated context.", ["project-management", "cloud-file-storage"]),
  e("Timezones", "dst-missing-time", "A local appointment time does not exist", "Spring-forward skips wall-clock instants.", "Scheduler silently moves or duplicates a booking.", "Use IANA zones and an explicit skip/reject policy; test transition dates.", ["appointment-saas", "hotel-pms"]),
  e("Timezones", "dst-repeated-time", "A local time occurs twice", "Fall-back produces two UTC instants for one wall time.", "Wrong slot or night charge is selected.", "Store the chosen instant and offset; require disambiguation in rule expansion.", ["appointment-saas", "hotel-pms"]),
  e("Distributed Systems", "lock-holder-resumes", "Expired lock holder resumes", "A process pauses past its lease while another acquires it.", "Both mutate the resource.", "Prefer database ownership; if a lease is unavoidable, use monotonic fencing checked by the resource.", ["video-streaming"]),
  e("Distributed Systems", "cursor-after-deletion", "Page cursor points across deleted rows", "The ordered set changes between page requests.", "Items are skipped or repeated.", "Use keyset cursor over immutable sort tuple and define tombstone/window behavior.", ["project-management", "social-network", "cloud-file-storage"]),
  e("Distributed Systems", "clock-skew-expiry", "Nodes disagree about expiry", "Wall clocks drift and messages are delayed.", "One service accepts an already expired offer/token.", "Evaluate expiry at the authoritative service/database with tolerance; use durations on clients only for display.", ["food-delivery", "ride-hailing", "payment-platform"]),
];

export const edgeCaseBySlug = new Map(edgeCases.map((item) => [item.slug, item]));
