import type { Project } from "@/lib/types";
import meta from "./metadata.json";
import { baseObservability, diagrams, scale } from "../helpers";

const project: Project = {
  ...meta, difficulty: "Expert",
  purpose: "Support profiles, follows, posts, media, home feeds, interactions, notifications, and moderation while respecting privacy and high-degree graph behavior.",
  assumptions: ["Follow graph can be directed", "Accounts may be private", "Feed ordering starts chronological with policy filters", "Counters are projections"],
  nonGoals: ["Advertising auction", "Opaque engagement ranking", "End-to-end encrypted messaging", "Replicating any named network"],
  journeys: [{ name: "Publish", steps: ["Authorize account", "Finalize scanned media", "Create post", "Write durable post/outbox", "Fan out to ordinary followers", "Leave celebrity posts for read-time merge", "Notify mentions"] }, { name: "Read feed", steps: ["Load feed cursor", "Merge precomputed inbox with followed high-fanout authors", "Filter blocks/privacy/deletions", "Hydrate authorized posts", "Return stable cursor"] }],
  requirements: { must: ["Profiles and follow lifecycle", "Text/media posts", "Home feed", "Likes/comments", "Block/report/moderation"], should: ["Private accounts", "Mentions", "Notifications", "Post edit history"], future: ["Groups", "Federation", "Recommendations", "Direct messages"] },
  nfrs: [{ concern: "Availability", decision: "Post writes survive feed-worker outages; feeds may be delayed with freshness shown internally." }, { concern: "Consistency", decision: "Privacy/block/follow acceptance is authoritative; feeds and counters converge." }, { concern: "Scalability", decision: "Hybrid fan-out prevents one high-degree author from overwhelming write fan-out." }, { concern: "Safety", decision: "Moderation, reports, rate limits, and appeals are first-class workflows." }, { concern: "Privacy", decision: "Audience is checked again when hydrating feed candidates." }],
  roles: [{ role: "Member", access: "Own profile/posts; authorized social content" }, { role: "Moderator", access: "Queued reports/content with audited decisions" }, { role: "Support", access: "Account recovery metadata, not unrestricted content" }, { role: "Safety admin", access: "Policy configuration and restricted appeals" }],
  entities: [{ name: "Account → FollowEdge", relationship: "Directed requested/accepted relationship" }, { name: "Account → Post → Media", relationship: "Author owns post; media publish follows scan" }, { name: "Post → Reaction / Comment", relationship: "Interactions have uniqueness/audience checks" }, { name: "Account → FeedItem", relationship: "Materialized candidate with source post" }, { name: "Report → ModerationDecision", relationship: "Evidence and reversible policy action" }],
  tables: [
    { name: "follows", purpose: "Directed social graph", columns: ["follower_id UUID", "followed_id UUID", "status TEXT", "created_at TIMESTAMPTZ"], constraints: ["PK(follower_id, followed_id)", "follower_id <> followed_id"], indexes: ["(followed_id, status, follower_id)", "(follower_id, status)"] },
    { name: "posts", purpose: "Authoritative post", columns: ["id UUID PK", "author_id UUID FK", "body TEXT", "audience TEXT", "status TEXT", "created_at TIMESTAMPTZ", "version INT"], constraints: ["bounded body length"], indexes: ["(author_id, created_at DESC, id DESC)", "(status, created_at)"] },
    { name: "feed_items", purpose: "Per-user feed candidates", columns: ["user_id UUID", "post_id UUID", "author_id UUID", "sort_key BIGINT", "created_at TIMESTAMPTZ"], constraints: ["PK(user_id, post_id)"], indexes: ["(user_id, sort_key DESC, post_id DESC)"] },
    { name: "moderation_actions", purpose: "Audited policy decisions", columns: ["id UUID PK", "target_type TEXT", "target_id UUID", "actor_id UUID", "policy TEXT", "action TEXT", "reason TEXT", "created_at TIMESTAMPTZ"], constraints: ["append-only"], indexes: ["(target_type, target_id, created_at)"] },
  ],
  transactions: ["Post and outbox commit atomically", "Accept private follow conditionally changes requested edge", "Block transaction deletes/conflicts follow edges and increments privacy epoch", "Hard delete media only after tombstone propagation/retention; moderation actions remain audited"],
  endpoints: [{ method: "POST", path: "/v1/posts", purpose: "Publish post with finalized media ids", permission: "Member", idempotency: "Client mutation id", responses: "201, 422, 429" }, { method: "GET", path: "/v1/feed?cursor=…", purpose: "Stable keyset feed", permission: "Member", responses: "200" }, { method: "POST", path: "/v1/accounts/:id/follows", purpose: "Follow or request follow", permission: "Member; block rules", idempotency: "Unique edge", responses: "200, 403, 409" }, { method: "POST", path: "/v1/posts/:id/reactions", purpose: "Set reaction", permission: "Authorized viewer", idempotency: "Upsert by user/post/type", responses: "200, 403" }, { method: "POST", path: "/v1/reports", purpose: "Report content/account", permission: "Member with rate limit", idempotency: "Client report id", responses: "201, 429" }, { method: "DELETE", path: "/v1/posts/:id", purpose: "Tombstone own post", permission: "Author or policy-authorized moderator", idempotency: "Idempotent", responses: "204, 403" }],
  events: [{ name: "PostPublished", producer: "Post API", consumers: "Feed fan-out, search, mention notification", delivery: "Outbox; feed unique(user,post)" }, { name: "PrivacyChanged", producer: "Graph API", consumers: "Feed repair, cache invalidation", delivery: "Epoch/version; hydration remains final guard" }, { name: "ContentRemoved", producer: "Moderation", consumers: "Feed/search/media purge", delivery: "High priority, replayable tombstone" }],
  failures: [{ name: "Fan-out lag", failure: "Post exists but followers do not see it yet.", mitigation: "Durable outbox/queue, lag metric, and author-profile read remains authoritative." }, { name: "Celebrity explosion", failure: "Millions of follower writes per post.", mitigation: "Classify high-fanout authors and merge their posts at read time." }, { name: "Privacy race", failure: "User becomes private/blocks after item entered feed.", mitigation: "Hydration rechecks current audience/block epoch before returning content." }, { name: "Duplicate like", failure: "Client retries reaction.", mitigation: "Unique user/post/type upsert; counters consume change events idempotently." }, { name: "Deleted post remains", failure: "Stale cache/feed references tombstoned post.", mitigation: "Hydration omits tombstones; removal event and short negative cache accelerate cleanup." }, { name: "Moderation retry", failure: "Same action is applied twice.", mitigation: "Decision idempotency id and state-aware reversible actions." }],
  consistency: { strong: ["Account/block/privacy state", "Post ownership", "follow edge", "moderation decision"], eventual: ["Home feed", "reaction/follower counts", "search", "notifications"] },
  concurrency: ["Unique graph/reaction constraints absorb retries", "Privacy epoch invalidates cached audience decisions", "Post version protects edits", "Feed insertion is idempotent; no per-user distributed lock"],
  caching: { cache: ["Public profile/post with audience epoch", "Media via CDN", "Feed page briefly per user/version"], never: ["Block decision without epoch", "Unreviewed uploads", "Moderator evidence in shared caches"], policy: "Cache public immutable media aggressively. Audience-sensitive objects include policy epoch and are reauthorized on hydration." },
  jobs: ["Feed fan-out/repair", "Media scan/transcode", "Counter aggregation", "Search indexing/removal", "Notifications", "Abuse classification and retention purge"],
  security: ["Object-level audience/block checks", "Sanitize text/links and proxy or validate remote previews against SSRF", "Scan and re-encode uploads", "Rate-limit follows, posts, comments, reports by behavioral signals", "Moderator access/actions are least-privilege and audited", "Prevent account enumeration in private/recovery flows", "Deletion and export honor retention/legal constraints explicitly"],
  observability: baseObservability("feed fan-out lag, hydration filter rate, report backlog, and media processing failures"),
  testing: [{ layer: "Unit", coverage: "Audience policy matrix, cursors, post state, fan-out classifier" }, { layer: "Integration", coverage: "Graph uniqueness, outbox, tombstone filters, privacy epoch" }, { layer: "Contract", coverage: "Versioned feed and moderation events" }, { layer: "Concurrency", coverage: "Follow/block races and duplicate reactions" }, { layer: "Failure", coverage: "Fan-out outage, stale cache, deletion replay" }, { layer: "Load", coverage: "Skewed follower graph and celebrity post bursts" }],
  deployment: [{ stage: "Stage 1", stack: "Modular API, PostgreSQL, queue/workers, object storage/CDN, Redis" }, { stage: "Stage 2", stack: "Feed service/store, search, media pipeline, realtime/notification workers" }, { stage: "Stage 3", stack: "Account/graph and feed partitions; hybrid fan-out; regional media delivery" }],
  scale: scale("Introduce hybrid fan-out, separate feed store/search/media workers, read replicas for profiles", "Partition graph/posts by account and feeds by recipient; use explicit routing and accept eventual cross-partition timelines"),
  diagrams: diagrams("Member --> Platform\nModerator --> Platform\nPlatform --> ObjectStorage\nPlatform --> CDN\nPlatform --> NotificationProvider", "Apps --> API\nAPI --> PostgreSQL\nAPI --> Redis\nAPI --> ObjectStorage\nPostgreSQL --> Queue\nQueue --> FeedWorker\nQueue --> SearchIndexer\nFeedWorker --> FeedStore", "Author->>API: POST /posts\nAPI->>PostgreSQL: post + outbox\nQueue-->>FeedWorker: PostPublished\nFeedWorker->>FeedStore: insert ordinary follower items\nReader->>API: GET /feed\nAPI->>FeedStore: candidates\nAPI->>PostgreSQL: hydrate + audience filter\nAPI-->>Reader: authorized feed"),
};
export default project;
