import type { Project } from "@/lib/types";
import meta from "./metadata.json";
import { diagrams, scale } from "../helpers";

const project: Project = {
  ...meta, difficulty: "Expert",
  purpose: "Accept source videos, produce validated adaptive renditions, authorize playback, and deliver segments efficiently through a CDN.",
  assumptions: ["Video on demand, not live streaming", "Object storage is the durable media store", "A CDN serves immutable segments", "Entitlement rules exist but billing is external"],
  nonGoals: ["Codec implementation", "Global rights negotiation", "Claiming a specific commercial platform architecture", "User-generated livestreaming"],
  journeys: [{ name: "Publish", steps: ["Create upload session", "Upload source directly in parts", "Finalize and verify checksum", "Probe file", "Transcode renditions", "Package manifest", "Run moderation/QC", "Atomically publish asset version"] }, { name: "Play", steps: ["Authorize viewer and region/device", "Issue short-lived playback token", "Fetch manifest through edge", "Player adapts bitrate", "Send sampled quality telemetry"] }],
  requirements: { must: ["Resumable direct upload", "Transcode pipeline", "Adaptive bitrate packaging", "Playback authorization", "CDN delivery and lifecycle"], should: ["Captions", "Thumbnails", "Moderation review", "Resume position"], future: ["Live video", "Offline licenses", "Personalization", "Multi-CDN steering"] },
  nfrs: [{ concern: "Durability", decision: "Source and published renditions use versioned object storage; metadata references immutable keys." }, { concern: "Availability", decision: "Published playback continues from CDN during control-plane degradation." }, { concern: "Latency", decision: "Startup depends on compact manifests and nearby first segments; ingest throughput is asynchronous." }, { concern: "Consistency", decision: "Asset publication is atomic at a version pointer; view analytics are eventual." }, { concern: "Security", decision: "Upload and playback grants are narrow, expiring, and never expose storage credentials." }],
  roles: [{ role: "Viewer", access: "Entitled published assets" }, { role: "Publisher", access: "Own uploads, metadata, publication" }, { role: "Moderator", access: "Review queue and policy outcome" }, { role: "Operations", access: "Pipeline replay/quarantine, audited" }],
  entities: [{ name: "Video → VideoVersion", relationship: "Metadata points to one published immutable version" }, { name: "UploadSession → UploadPart", relationship: "Tracks resumable source ingest" }, { name: "VideoVersion → Rendition → Segment", relationship: "Package describes bitrate-specific immutable objects" }, { name: "VideoVersion → ProcessingJob", relationship: "Stage/attempt workflow" }, { name: "Viewer → PlaybackGrant", relationship: "Short-lived entitlement decision" }],
  tables: [
    { name: "video_versions", purpose: "Immutable processing/publication unit", columns: ["id UUID PK", "video_id UUID FK", "source_key TEXT", "status TEXT", "manifest_key TEXT NULL", "checksum TEXT", "created_at TIMESTAMPTZ"], constraints: ["UNIQUE(source_key)", "manifest required when published"], indexes: ["(video_id, created_at DESC)", "(status, created_at)"] },
    { name: "upload_sessions", purpose: "Bounded direct upload grant", columns: ["id UUID PK", "publisher_id UUID FK", "object_key TEXT", "expected_size BIGINT", "status TEXT", "expires_at TIMESTAMPTZ"], constraints: ["UNIQUE(object_key)", "expected_size > 0"], indexes: ["(status, expires_at)"] },
    { name: "processing_jobs", purpose: "Resumable pipeline stages", columns: ["id UUID PK", "video_version_id UUID FK", "stage TEXT", "attempt INT", "status TEXT", "input_hash TEXT", "lease_until TIMESTAMPTZ"], constraints: ["UNIQUE(video_version_id, stage, input_hash)"], indexes: ["(status, lease_until)"] },
    { name: "playback_progress", purpose: "User resume projection", columns: ["viewer_id UUID", "video_id UUID", "position_ms BIGINT", "updated_at TIMESTAMPTZ", "version INT"], constraints: ["PK(viewer_id, video_id)"], indexes: ["(viewer_id, updated_at DESC)"] },
  ],
  transactions: ["Finalize verifies provider-reported parts/checksum then marks session complete and enqueues probe via outbox", "Publish switches current_version_id only after all required outputs and moderation pass", "Processing jobs use leases and unique stage/input hash", "Delete metadata first marks unavailable; media lifecycle deletion is delayed and recoverable"],
  endpoints: [{ method: "POST", path: "/v1/uploads", purpose: "Create bounded multipart upload", permission: "Publisher", idempotency: "Required", responses: "201, 413, 429" }, { method: "POST", path: "/v1/uploads/:id/complete", purpose: "Verify object and begin processing", permission: "Session owner", idempotency: "Same parts/checksum returns result", responses: "202, 409, 422" }, { method: "GET", path: "/v1/videos/:id", purpose: "Read published metadata", permission: "Catalog visibility", responses: "200, 404" }, { method: "POST", path: "/v1/videos/:id/playback-grants", purpose: "Authorize short-lived manifest access", permission: "Entitled viewer", idempotency: "Not required; token is short-lived", responses: "201, 403, 451" }, { method: "PATCH", path: "/v1/videos/:id/publish", purpose: "Switch published version", permission: "Publisher/moderator policy", idempotency: "Version precondition", responses: "200, 409, 422" }],
  events: [{ name: "UploadFinalized", producer: "Upload API", consumers: "Probe worker", delivery: "Outbox; unique stage/input hash" }, { name: "RenditionCompleted", producer: "Transcoder", consumers: "Packaging coordinator", delivery: "At-least-once and checks output checksum" }, { name: "VideoPublished", producer: "Catalog", consumers: "CDN prewarm, search, notifications", delivery: "Versioned and replayable" }],
  failures: [{ name: "Metadata without object", failure: "Upload finalize claims success but object is missing.", mitigation: "HEAD/checksum before transaction; do not trust client-reported completion." }, { name: "Worker crash", failure: "Transcoder dies after writing some segments.", mitigation: "Write attempt-specific prefix, lease job, validate complete outputs, then promote by metadata pointer." }, { name: "Duplicate job", failure: "Same stage executes twice.", mitigation: "Unique input hash and deterministic immutable outputs; only one state transition wins." }, { name: "Poison media", failure: "Malformed source crashes codec tooling.", mitigation: "Sandbox workers, resource limits, file probing, quarantine and bounded retries." }, { name: "Premature publish", failure: "Manifest references missing renditions.", mitigation: "Publication transaction checks required stage/QC records and immutable objects." }, { name: "Token leak", failure: "Playback URL is shared.", mitigation: "Short TTL, scope to asset/region/device policy, optional cookie-based segment authorization." }],
  consistency: { strong: ["Upload finalization", "processing stage state", "published-version pointer", "entitlement at grant issuance"], eventual: ["CDN fill/purge", "view counts", "search index", "resume position"] },
  concurrency: ["Unique stage/input constraint prevents duplicate logical jobs", "Lease with compare-and-set supports worker recovery", "Publish uses expected current version", "Progress uses monotonic client timestamp/version, not blind last arrival"],
  caching: { cache: ["Immutable segments for long TTL", "Versioned manifests", "Published metadata", "Entitlement-independent catalog"], never: ["Raw source", "moderation-only content", "long-lived entitlement decision"], policy: "Content-addressed/versioned media gets immutable caching. Playback grants are short-lived; revoke through key/version rotation for urgent cases." },
  jobs: ["Probe", "Transcode fan-out", "Package manifests", "Generate thumbnails/captions", "Moderation/QC", "Orphan cleanup and storage lifecycle"],
  security: ["Presigned uploads restrict object key, type, size, and expiry", "Untrusted media processed in network-isolated, resource-limited workers", "Playback grants enforce entitlement and territorial/device rules", "Private origins accept only CDN/service identity", "Validate filenames and never pass user strings to shell", "Audit publish/unpublish and moderation", "Protect telemetry endpoint from amplification and fabricated views"],
  observability: { logs: ["Upload finalize verification with version, object metadata, and checksum result", "Processing stage lease, input hash, worker image, attempt, and output validation", "Publication/entitlement decision without playback token or source URL"], metrics: ["Multipart completion and abandoned-upload rate", "Transcode queue age, encode duration, and failure rate by codec/rendition", "Publish lead time and missing-output validation failures", "Playback startup, rebuffer ratio, manifest errors, and CDN origin miss rate"], traces: ["Trace upload finalization through probe, transcode fan-out, packaging, QC, and publish", "Sample playback-grant and origin-miss paths without tracing every media segment"], alerts: ["Oldest required transcode stage breaches publish SLO", "CDN origin error/miss surge threatens playback", "Published manifest validation or entitlement service failure rises materially"] },
  testing: [{ layer: "Unit", coverage: "Pipeline state machine, entitlement rules, manifest builder" }, { layer: "Integration", coverage: "Multipart finalize, queue leases, object checks, publish gate" }, { layer: "Contract", coverage: "Object/CDN APIs and player manifest fixtures" }, { layer: "Concurrency", coverage: "Duplicate stage execution, stale leases, and simultaneous publish attempts" }, { layer: "Failure", coverage: "Worker death, corrupt input, missing segment, stale lease" }, { layer: "End-to-end", coverage: "Upload small fixtures → publish → authorized playback" }, { layer: "Load", coverage: "Ingest burst and playback cache-miss workload; report assumptions" }],
  deployment: [{ stage: "Stage 1", stack: "Control API, PostgreSQL, object storage, managed queue, autoscaled media workers, CDN" }, { stage: "Stage 2", stack: "Stage-specific worker pools, separate metadata/read API, origin shielding, read replica" }, { stage: "Stage 3", stack: "Regional ingest and multi-CDN delivery; globally replicated catalog with a controlled publisher" }],
  scale: scale({ start: ["One API, PostgreSQL for the catalog and processing jobs, object storage for sources and renditions, a transcode worker, a CDN", "Make every processing stage idempotent and resumable; publish a title only after every required rendition exists"], middle: ["Scale CPU/GPU worker pools by queue/stage; use CDN origin shield; isolate telemetry ingestion", "Scale worker pools on transcode queue age; add an origin shield when CDN origin misses drive storage egress"], large: ["Regional ingest and processing close to storage; multi-CDN only after measured availability/performance need; immutable media avoids cross-region writes", "Process near the ingest region's storage; add CDNs or regions only for measured playback-startup or availability gaps"] }),
  diagrams: diagrams("Publisher --> Platform\nViewer --> Platform\nPlatform --> ObjectStorage\nPlatform --> CDN\nPlatform --> ModerationProvider", "Publisher --> UploadAPI\nUploadAPI --> ObjectStorage\nUploadAPI --> PostgreSQL\nPostgreSQL --> Queue\nQueue --> TranscodeWorkers\nTranscodeWorkers --> ObjectStorage\nViewer --> CDN\nCDN --> ObjectStorage", "Publisher->>UploadAPI: complete(parts, checksum)\nUploadAPI->>ObjectStorage: verify object\nUploadAPI->>PostgreSQL: finalized + outbox\nQueue-->>Transcoder: probe/transcode\nTranscoder->>ObjectStorage: immutable renditions\nTranscoder->>PostgreSQL: stage complete\nPublisher->>UploadAPI: publish version\nUploadAPI->>PostgreSQL: validate and switch pointer"),
};
export default project;
