import type { Project } from "@/lib/types";
import meta from "./metadata.json";
import { diagrams, scale } from "../helpers";

const project: Project = {
  ...meta, difficulty: "Expert",
  purpose: "Teach safe payment orchestration around a regulated provider: payment intents, tokenized methods, idempotent commands, append-only ledger concepts, verified webhooks, and reconciliation.",
  assumptions: ["A compliant payment service provider collects and tokenizes card details", "The platform stores provider tokens, never raw card data or CVV", "The illustrative ledger is not a bank ledger", "Production use requires legal, security, PCI, tax, and jurisdiction-specific review"],
  nonGoals: ["Processing card numbers directly", "Holding deposits as a bank", "Giving compliance certification advice", "Implementing card-network protocols"],
  journeys: [{ name: "Create and confirm payment", steps: ["Merchant creates intent with idempotency key", "Server records amount/currency/status", "Client uses provider-hosted collection", "Merchant confirms intent", "Provider may require customer action", "Webhook/reconciliation determines authoritative provider outcome", "Post balanced internal ledger entries"] }, { name: "Refund", steps: ["Lock payment/refundable aggregate", "Validate amount and merchant", "Create pending refund", "Call provider using stable reference", "Apply verified webhook/result", "Post reversal entries", "Reconcile"] }],
  requirements: { must: ["Tenant-scoped payment intents", "Provider token orchestration", "Idempotent confirm/refund", "Verified webhook inbox", "Balanced append-only ledger and reconciliation"], should: ["Partial capture/refund", "Provider adapter", "Disputes projection", "Operational exceptions queue"], future: ["Multiple providers", "Payout orchestration", "Risk rules", "Multi-currency conversion"] },
  nfrs: [{ concern: "Correctness", decision: "Money uses integer minor units and ISO currency; every mutation has durable idempotency and state preconditions." }, { concern: "Durability", decision: "Ledger postings and resulting domain transition commit atomically; provider state is reconciled." }, { concern: "Availability", decision: "Ambiguous provider outcomes become pending, never guessed success/failure." }, { concern: "Security", decision: "Card entry stays on provider-hosted fields; secrets are vault-managed, scoped, and rotated." }, { concern: "Auditability", decision: "Commands, webhooks, ledger entries, overrides, and reconciliation outcomes are immutable/audited." }],
  roles: [{ role: "Merchant service", access: "Own tenant intents/refunds using scoped API credential" }, { role: "Finance operator", access: "Tenant reports and controlled exception resolution" }, { role: "Risk analyst", access: "Risk signals/holds; no secret or raw instrument access" }, { role: "Platform operator", access: "Provider health and replay controls with dual control" }],
  entities: [{ name: "Merchant → PaymentIntent → PaymentAttempt", relationship: "Intent is merchant goal; attempts record provider interactions" }, { name: "PaymentIntent → Capture / Refund", relationship: "Amount-limited state transitions" }, { name: "LedgerTransaction → LedgerEntry", relationship: "At least two entries sum to zero per currency" }, { name: "WebhookInbox", relationship: "Verified provider event id and processing state" }, { name: "IdempotencyRecord", relationship: "Merchant/key binds request hash to stored response" }, { name: "ReconciliationException", relationship: "Explicit mismatch workflow" }],
  tables: [
    { name: "payment_intents", purpose: "Merchant payment aggregate", columns: ["id UUID PK", "merchant_id UUID FK", "merchant_reference TEXT", "amount_minor BIGINT", "currency CHAR(3)", "status TEXT", "provider_ref TEXT NULL", "version INT"], constraints: ["UNIQUE(merchant_id, merchant_reference)", "amount_minor > 0"], indexes: ["(merchant_id, created_at DESC)", "(status, updated_at)"] },
    { name: "idempotency_records", purpose: "Replay-safe command result", columns: ["merchant_id UUID", "key TEXT", "request_hash TEXT", "status TEXT", "response_code INT", "response_body JSONB", "expires_at TIMESTAMPTZ"], constraints: ["PK(merchant_id, key)"], indexes: ["(expires_at)"] },
    { name: "ledger_transactions", purpose: "Posting envelope", columns: ["id UUID PK", "merchant_id UUID", "source_type TEXT", "source_id UUID", "currency CHAR(3)", "created_at TIMESTAMPTZ"], constraints: ["UNIQUE(merchant_id, source_type, source_id)"], indexes: ["(merchant_id, created_at, id)"] },
    { name: "ledger_entries", purpose: "Immutable debit/credit amount", columns: ["id UUID PK", "transaction_id UUID FK", "account_id UUID FK", "amount_minor BIGINT", "currency CHAR(3)"], constraints: ["amount_minor <> 0", "deferred validation: sum per transaction/currency = 0", "no update/delete"], indexes: ["(account_id, id)"] },
    { name: "webhook_inbox", purpose: "Verified provider message receipt", columns: ["provider TEXT", "provider_event_id TEXT", "received_at TIMESTAMPTZ", "payload_ref TEXT", "status TEXT", "attempts INT"], constraints: ["PK(provider, provider_event_id)"], indexes: ["(status, received_at)"] },
  ],
  transactions: ["Reserve idempotency key/request hash before side effect; concurrent identical call waits or returns in-progress", "Apply valid payment transition and balanced ledger transaction atomically", "Refund creation locks payment aggregate and sums completed/pending refunds", "Never edit ledger entries; correct with linked reversal", "External provider call is outside DB transaction and uses stable provider idempotency reference"],
  endpoints: [{ method: "POST", path: "/v1/payment-intents", purpose: "Create merchant payment intent", permission: "Merchant credential with payments:write", idempotency: "Required; merchant scoped and payload hashed", responses: "201, 409, 422" }, { method: "POST", path: "/v1/payment-intents/:id/confirm", purpose: "Begin/continue provider confirmation", permission: "Owning merchant/customer secret boundary", idempotency: "Required", responses: "200, 202, 402, 409" }, { method: "GET", path: "/v1/payment-intents/:id", purpose: "Read platform state", permission: "Owning merchant or restricted client secret view", responses: "200, 403, 404" }, { method: "POST", path: "/v1/refunds", purpose: "Request full/partial refund", permission: "Merchant refunds:write", idempotency: "Required", responses: "201, 202, 409, 422" }, { method: "POST", path: "/v1/webhooks/provider", purpose: "Receive provider event", permission: "Verified signature/timestamp; not user auth", idempotency: "Provider event id unique", responses: "200, 400" }, { method: "GET", path: "/v1/balance-transactions?cursor=…", purpose: "Keyset ledger view", permission: "Merchant finance read", responses: "200, 403" }],
  events: [{ name: "PaymentSucceeded", producer: "Payment state machine", consumers: "Merchant webhook delivery, reconciliation projection", delivery: "Outbox; merchant delivery signed, retried with backoff, event-id dedupe" }, { name: "RefundSucceeded", producer: "Refund workflow", consumers: "Merchant webhook, reports", delivery: "At-least-once; immutable event id" }, { name: "ReconciliationMismatchFound", producer: "Reconciler", consumers: "Exception queue/alerting", delivery: "Unique provider object + settlement window; never auto-adjust silently" }],
  failures: [{ name: "Provider succeeded, response lost", failure: "Confirm times out after provider charge.", mitigation: "Intent remains processing; query by stable provider reference/idempotency key and reconcile." }, { name: "Duplicate merchant request", failure: "Retry could create a second payment/refund.", mitigation: "Merchant-scoped idempotency record binds key to request hash and stored result." }, { name: "Duplicate/out-of-order webhook", failure: "Provider events repeat or arrive late.", mitigation: "Verify, store unique event id, and apply only legal monotonic state transitions; retrieve provider object if needed." }, { name: "Refund race", failure: "Concurrent partial refunds exceed captured amount.", mitigation: "Lock payment/refundable row and include pending refunds in available amount." }, { name: "Ledger worker crash", failure: "Payment changes without accounting entry.", mitigation: "State transition and balanced posting share one database transaction." }, { name: "Platform/provider mismatch", failure: "Provider settlement differs from internal records.", mitigation: "Scheduled reconciliation creates explicit exception; humans resolve with audited reversal/adjustment." }],
  consistency: { strong: ["Idempotency outcome", "legal payment transitions", "refundable amount", "balanced ledger posting"], eventual: ["Merchant webhook delivery", "provider convergence after ambiguity", "reports", "settlement reconciliation completion"] },
  concurrency: ["Unique merchant/idempotency key plus request hash", "Payment aggregate row lock for refund/capture limits", "Unique ledger source prevents double posting", "Webhook unique provider event id", "No distributed lock is a substitute for these constraints"],
  caching: { cache: ["Public provider configuration by version", "Merchant display settings"], never: ["Payment state as command authority", "Available refundable amount", "Balances", "Idempotency result before durable completion"], policy: "Payment reads may use a brief projection only if freshness is visible; all money decisions use PostgreSQL. Never cache secrets." },
  jobs: ["Provider status reconciliation", "Webhook inbox processing", "Merchant webhook delivery with backoff", "Settlement-file reconciliation", "Idempotency retention cleanup", "Exception reporting"],
  security: ["Use provider-hosted/tokenized collection; never store PAN or CVV", "Vault provider/API secrets and rotate with overlapping keys", "Merchant credentials are scoped, hashed where applicable, and tenant-bound", "Verify webhook signature over raw body plus timestamp; dedupe event id", "Object-level merchant authorization on every intent/refund/ledger read", "Audit refund, replay, exception, and credential actions", "Rate-limit by credential, merchant, IP, and risk signal; do not log payment tokens or PII"],
  observability: { logs: ["Intent/attempt/refund transition with merchant, stable provider reference, idempotency key hash, and reason", "Webhook signature result, provider event id, inbox state, and legal-transition decision", "Ledger transaction source and account ids without tokens or customer payment data"], metrics: ["Authorization success/decline/ambiguous outcome by provider reason class", "Payment-processing age and provider retrieval reconciliation latency", "Webhook receipt-to-apply age, duplicate rate, and merchant delivery backlog", "Ledger balance-check failures and settlement reconciliation exception count"], traces: ["Trace confirm across idempotency reservation, provider call, state transition, ledger posting, and outbox", "Trace refund across refundable lock, provider ambiguity, webhook convergence, and reversal posting"], alerts: ["Any unbalanced ledger transaction or posting invariant failure", "Processing payments exceed the ambiguity-resolution window", "Webhook or settlement reconciliation backlog threatens financial reporting"] },
  testing: [{ layer: "Unit", coverage: "Money/currency, state machine, idempotency hash, ledger balance" }, { layer: "Integration", coverage: "Real PostgreSQL locks/constraints, atomic posting, webhook inbox/outbox" }, { layer: "Contract", coverage: "Provider sandbox and signed merchant webhook versions" }, { layer: "Concurrency", coverage: "Same idempotency key, partial refund races, webhook/confirm race" }, { layer: "Failure", coverage: "Timeout after provider success, out-of-order events, worker crash" }, { layer: "End-to-end/load", coverage: "Intent → action → success → refund → reconciliation; workload stated explicitly" }],
  deployment: [{ stage: "Stage 1", stack: "Private payment API, PostgreSQL, queue/workers, provider SDK, secret manager" }, { stage: "Stage 2", stack: "Separated webhook ingress, command API and reconciliation workers; primary/standby database" }, { stage: "Stage 3", stack: "Region/merchant cells with a single writer per payment; isolated ledger/reconciliation controls and replicated read reports" }],
  scale: scale("Scale stateless APIs/webhook ingest and workers independently; keep payment+ledger transaction on one primary", "Partition by merchant or payment home region; route all lifecycle commands to one owner and aggregate immutable events for reporting"),
  diagrams: diagrams("Merchant --> PaymentPlatform\nCustomer --> ProviderHostedUI\nPaymentPlatform --> PaymentProvider\nFinanceOperator --> PaymentPlatform", "Merchant --> API\nAPI --> PostgreSQL\nAPI --> PaymentProvider\nPaymentProvider --> WebhookIngress\nWebhookIngress --> Queue\nQueue --> StateWorker\nPostgreSQL --> Reconciler\nReconciler --> PaymentProvider", "Merchant->>API: confirm intent + Idempotency-Key\nAPI->>PostgreSQL: reserve key; mark processing\nAPI->>PaymentProvider: confirm(stable reference)\nalt response received\nPaymentProvider-->>API: succeeded\nAPI->>PostgreSQL: transition + balanced ledger + outbox\nAPI-->>Merchant: 200 succeeded\nelse timeout\nAPI-->>Merchant: 202 processing\nReconciler->>PaymentProvider: retrieve reference\nReconciler->>PostgreSQL: converge state + ledger\nend"),
};
export default project;
