import type { Project } from "@/lib/types";
import meta from "./metadata.json";
import { diagrams, scale } from "../helpers";

const project: Project = {
  ...meta, difficulty: "Intermediate",
  purpose: "Let service businesses publish availability and accept appointments without double booking across tenant rules, time zones, payments, and external calendars.",
  assumptions: ["Each organization is a tenant", "Availability is computed from rules plus exceptions", "External calendars are advisory until synchronized", "All stored instants are UTC with an IANA zone for presentation"],
  nonGoals: ["Medical records", "Calendar provider replacement", "Workforce payroll", "Arbitrary resource optimization"],
  journeys: [{ name: "Book", steps: ["Choose service and practitioner", "Compute candidate slots", "Create expiring slot hold", "Collect deposit if required", "Confirm appointment in transaction", "Publish notification/calendar jobs"] }, { name: "Reschedule", steps: ["Authorize appointment", "Hold new slot", "Validate policy", "Atomically move booking and release old capacity", "Update calendars and notifications"] }],
  requirements: { must: ["Tenant-scoped services and staff", "Recurring availability with exceptions", "Race-safe booking", "Cancellation/reschedule policy", "Reminders"], should: ["Deposits", "Group capacity", "External calendar sync", "Tenant booking page"], future: ["Waitlists", "Round-robin assignment", "Packages", "Marketplace discovery"] },
  nfrs: [{ concern: "Consistency", decision: "Booking capacity is strongly enforced; reminders and external calendars converge." }, { concern: "Tenant isolation", decision: "organization_id participates in every ownership query and uniqueness boundary." }, { concern: "Timezones", decision: "Rules use wall time plus IANA zone; concrete slots are UTC instants." }, { concern: "Availability", decision: "Existing schedules remain readable if calendar providers fail; sync status is explicit." }, { concern: "Privacy", decision: "Collect only scheduling details and restrict practitioner notes." }],
  roles: [{ role: "Customer", access: "Own appointments via account or signed management link" }, { role: "Practitioner", access: "Own schedule and assigned appointments" }, { role: "Receptionist", access: "Tenant appointments and customers; limited settings" }, { role: "Tenant admin", access: "Membership, services, policies, integrations, audit" }],
  entities: [{ name: "Organization → Membership", relationship: "Membership establishes tenant role" }, { name: "Service → Practitioner", relationship: "Eligibility and duration define bookable offering" }, { name: "AvailabilityRule + Exception", relationship: "Rules generate candidates; exceptions block or add time" }, { name: "Appointment → ResourceBooking", relationship: "One appointment reserves practitioner/room capacity" }, { name: "Appointment → ExternalCalendarLink", relationship: "Tracks provider version and sync state" }],
  tables: [
    { name: "availability_rules", purpose: "Recurring local-time schedule", columns: ["id UUID PK", "organization_id UUID FK", "practitioner_id UUID FK", "weekday SMALLINT", "start_local TIME", "end_local TIME", "timezone TEXT", "valid_from DATE"], constraints: ["start_local < end_local"], indexes: ["(organization_id, practitioner_id, valid_from)"] },
    { name: "appointments", purpose: "Confirmed or held booking", columns: ["id UUID PK", "organization_id UUID FK", "practitioner_id UUID FK", "service_id UUID FK", "starts_at TIMESTAMPTZ", "ends_at TIMESTAMPTZ", "status TEXT", "hold_expires_at TIMESTAMPTZ", "version INT"], constraints: ["ends_at > starts_at", "exclusion constraint on active practitioner time range"], indexes: ["(organization_id, practitioner_id, starts_at)", "(status, hold_expires_at)"] },
    { name: "notification_jobs", purpose: "Durable scheduled reminders", columns: ["id UUID PK", "organization_id UUID", "appointment_id UUID FK", "kind TEXT", "run_at TIMESTAMPTZ", "status TEXT", "appointment_version INT"], constraints: ["UNIQUE(appointment_id, kind, appointment_version)"], indexes: ["(status, run_at)"] },
  ],
  transactions: ["PostgreSQL time-range exclusion constraint is final authority for a practitioner booking", "Reschedule holds new capacity and releases old in one transaction", "Appointment plus outbox commits together", "Hard-delete expired unauthenticated holds; retain appointment/audit according to tenant policy"],
  endpoints: [{ method: "GET", path: "/v1/booking/:tenant/services/:id/slots?from=&to=", purpose: "Return computed candidates", permission: "Public tenant page", responses: "200, 422" }, { method: "POST", path: "/v1/appointments/holds", purpose: "Temporarily reserve a slot", permission: "Customer or receptionist", idempotency: "Required", responses: "201, 409, 422" }, { method: "POST", path: "/v1/appointments/:id/confirm", purpose: "Confirm held appointment", permission: "Hold owner", idempotency: "Required", responses: "200, 402, 409, 410" }, { method: "POST", path: "/v1/appointments/:id/reschedule", purpose: "Move to a new slot", permission: "Customer link or tenant staff", idempotency: "Required", responses: "200, 409, 422" }, { method: "GET", path: "/v1/appointments?cursor=…", purpose: "Tenant schedule ordered by start/id", permission: "Tenant member", responses: "200, 403" }],
  events: [{ name: "AppointmentConfirmed", producer: "Scheduling", consumers: "Reminder, calendar sync", delivery: "Outbox; consumers key work by appointment/version" }, { name: "AppointmentRescheduled", producer: "Scheduling", consumers: "Reminder cancellation, calendar sync", delivery: "New version supersedes stale jobs" }, { name: "CalendarWebhookReceived", producer: "Webhook adapter", consumers: "Sync worker", delivery: "Signature checked, provider event id deduped" }],
  failures: [{ name: "Double booking", failure: "Two customers confirm the same slot.", mitigation: "Database exclusion/capacity constraint rejects one transaction." }, { name: "Hold expires during payment", failure: "Deposit succeeds after slot release.", mitigation: "Use bounded hold and payment intent; reconcile late success into refund or manual resolution, never silent booking." }, { name: "DST gap", failure: "Recurring 02:30 does not exist on transition day.", mitigation: "Timezone library resolves policy explicitly and tests transition dates." }, { name: "Calendar echo", failure: "Our update returns as a provider webhook.", mitigation: "Store provider event id and our external event reference; suppress semantic duplicates." }, { name: "Old reminder fires", failure: "Appointment was rescheduled after job creation.", mitigation: "Worker compares appointment version/status before send." }, { name: "Signed link forwarded", failure: "Another person manages the booking.", mitigation: "Short-lived, purpose-scoped, revocable token; require account/verification for sensitive details." }],
  consistency: { strong: ["Practitioner/resource capacity", "Hold conversion", "Reschedule", "deposit association"], eventual: ["External calendars", "reminders", "availability read cache", "analytics"] },
  concurrency: ["Time-range exclusion constraint beats application-only slot checks", "Optimistic version protects policy/status updates", "Unique reminder version prevents duplicate send scheduling", "Group bookings lock one capacity counter row"],
  caching: { cache: ["Service catalog", "Availability rule versions", "Short-lived generated slot candidates"], never: ["Slot validity at confirm", "Tenant membership", "Deposit result"], policy: "Cache candidate reads briefly by rule version; booking always attempts the database constraint." },
  jobs: ["Expire holds", "Send version-checked reminders", "Calendar push/pull sync", "Reconcile deposits", "Apply tenant retention"],
  security: ["Tenant scope derived from authenticated membership", "Object authorization for appointment and practitioner", "Signed booking links are scoped, expiring, and hashed at rest", "Webhook signature/replay verification", "Escape customer-entered text in notifications", "Rate-limit public slot enumeration and booking", "Keep sensitive notes out of calendar descriptions by default"],
  observability: { logs: ["Hold, confirm, reschedule, and cancel transitions with tenant, appointment version, and policy result", "Timezone/rule version used to generate a selected slot", "Calendar provider event id, echo suppression, and sync outcome"], metrics: ["Slot-query latency and confirmation conflict rate", "Hold conversion/expiry and late-deposit resolution count", "Reminder scheduling lateness and send suppression by stale version", "Calendar sync lag, webhook duplication, and provider error rate"], traces: ["Trace slot discovery through range-constraint booking and deposit confirmation", "Trace reschedule through new capacity reservation, old release, and provider sync"], alerts: ["Reminder queue is late enough to miss customer windows", "Calendar sync lag exceeds tenant promise", "Confirmed appointment count diverges from active capacity"] },
  testing: [{ layer: "Unit", coverage: "Recurrence and DST fixtures, cancellation policy, appointment state machine" }, { layer: "Integration", coverage: "PostgreSQL range conflicts, tenant boundaries, outbox" }, { layer: "Contract", coverage: "Calendar/provider webhook payloads" }, { layer: "Concurrency", coverage: "Two confirms and concurrent reschedule" }, { layer: "Failure", coverage: "Late payment, stale reminder, provider outage" }, { layer: "End-to-end", coverage: "Discover → hold → confirm → remind → reschedule/cancel" }],
  deployment: [{ stage: "Stage 1", stack: "Next.js, modular API, PostgreSQL, queue worker, email/calendar providers" }, { stage: "Stage 2", stack: "API replicas, Redis candidate cache, provider-specific sync workers, read replica" }, { stage: "Stage 3", stack: "Tenant cohorts and isolated enterprise databases where compliance/volume justify it" }],
  scale: scale("Replicate stateless API; cache candidate slots; isolate reminder and calendar workers", "Partition tenants into cohorts; route a tenant to one booking writer and provide enterprise isolation where justified"),
  diagrams: diagrams("Customer --> BookingSite\nStaff --> AdminApp\nBookingSite --> SchedulingAPI\nSchedulingAPI --> CalendarProvider\nSchedulingAPI --> PaymentProvider", "WebApps --> API\nAPI --> PostgreSQL\nAPI --> Redis\nPostgreSQL --> OutboxWorker\nOutboxWorker --> Queue\nQueue --> ReminderWorker\nQueue --> CalendarWorker", "Customer->>API: create hold\nAPI->>PostgreSQL: insert active time range\nAPI-->>Customer: hold + expiry\nCustomer->>API: confirm\nAPI->>PaymentProvider: confirm deposit\nAPI->>PostgreSQL: hold -> confirmed + outbox\nAPI-->>Customer: appointment confirmed"),
};
export default project;
