import type { Project } from "@/lib/types";
import meta from "./metadata.json";
import { diagrams, scale } from "../helpers";

const project: Project = {
  ...meta, difficulty: "Advanced",
  purpose: "Store large file bytes durably while providing tenant-safe folders, resumable uploads, versions, sharing, quota enforcement, scanning, and synchronized metadata.",
  assumptions: ["Object storage holds bytes; PostgreSQL owns namespace and permissions", "Workspace is a tenant boundary", "Files may have many immutable versions", "Clients upload directly with constrained grants"],
  nonGoals: ["Collaborative document editing", "Filesystem POSIX semantics", "Backup of arbitrary machines", "Content inspection beyond safety/policy"],
  journeys: [{ name: "Upload", steps: ["Authorize parent folder and reserve quota", "Create multipart session and object key", "Upload parts directly", "Finalize/check checksum", "Create quarantined file version", "Scan/type-check", "Publish version and notify clients"] }, { name: "Share", steps: ["Choose file/folder and permissions", "Create revocable hashed token or member ACL", "Recipient presents token", "Authorize current state", "Issue short-lived download URL", "Audit download where policy requires"] }],
  requirements: { must: ["Folders and file metadata", "Resumable upload/download", "Version history", "Member and link sharing", "Quota and malware scan"], should: ["Trash/restore", "Thumbnails", "Desktop sync change cursor", "Audit export"], future: ["Block-level delta sync", "End-user encryption", "Document collaboration", "Cross-workspace transfer"] },
  nfrs: [{ concern: "Durability", decision: "Published versions use durable versioned storage and checked metadata; deletion is delayed." }, { concern: "Consistency", decision: "Namespace, quota reservation, and ACL are transactional; scanning/preview and sync notifications converge." }, { concern: "Security", decision: "No raw bucket access; grants are narrow and files stay quarantined until checks complete." }, { concern: "Scalability", decision: "Large bytes bypass application servers; metadata pages use keyset cursors." }, { concern: "Privacy", decision: "Tenant keys, access logging, retention, and regional placement are explicit." }],
  roles: [{ role: "Member", access: "Workspace files granted by inherited ACL" }, { role: "Workspace admin", access: "Membership, policy, quota, audit; content access is separately governed" }, { role: "External recipient", access: "Only token-scoped shared object" }, { role: "Security operator", access: "Quarantine metadata and controlled sample access" }],
  entities: [{ name: "Workspace → Node", relationship: "Node is file or folder in one tenant namespace" }, { name: "File Node → FileVersion", relationship: "Immutable object metadata; one current published version" }, { name: "Node → ACL", relationship: "Direct grant with documented inheritance resolution" }, { name: "ShareLink → Node", relationship: "Hashed, expiring, revocable capability" }, { name: "UploadSession → QuotaReservation", relationship: "Bounds unfinished bytes" }, { name: "Workspace → Change", relationship: "Ordered metadata log drives sync" }],
  tables: [
    { name: "nodes", purpose: "Tenant namespace", columns: ["id UUID PK", "workspace_id UUID FK", "parent_id UUID NULL", "kind TEXT", "name TEXT", "current_version_id UUID NULL", "deleted_at TIMESTAMPTZ", "version INT"], constraints: ["UNIQUE(workspace_id, parent_id, normalized_name) WHERE deleted_at IS NULL", "folder cannot parent itself"], indexes: ["(workspace_id, parent_id, name, id)", "(workspace_id, deleted_at)"] },
    { name: "file_versions", purpose: "Immutable byte object reference", columns: ["id UUID PK", "workspace_id UUID", "file_id UUID FK", "object_key TEXT", "size_bytes BIGINT", "checksum TEXT", "status TEXT", "mime_detected TEXT"], constraints: ["UNIQUE(object_key)", "size_bytes >= 0"], indexes: ["(workspace_id, file_id, created_at DESC)", "(status, created_at)"] },
    { name: "acl_entries", purpose: "Explicit grants", columns: ["workspace_id UUID", "node_id UUID", "principal_type TEXT", "principal_id UUID", "permission TEXT"], constraints: ["PK(node_id, principal_type, principal_id, permission)"], indexes: ["(workspace_id, principal_id)"] },
    { name: "workspace_changes", purpose: "Monotonic sync feed", columns: ["seq BIGSERIAL", "workspace_id UUID", "node_id UUID", "kind TEXT", "node_version INT", "created_at TIMESTAMPTZ"], constraints: ["PK(workspace_id, seq) logically/partitioned"], indexes: ["(workspace_id, seq)"] },
  ],
  transactions: ["Reserve quota and create upload session together", "Finalize creates quarantined version; scan publishes current_version and change record atomically", "Move checks destination name uniqueness and prevents descendant cycles", "Trash is soft delete; object purge follows retention and legal hold asynchronously"],
  endpoints: [{ method: "GET", path: "/v1/nodes/:id/children?cursor=…", purpose: "List authorized child nodes", permission: "Node viewer", responses: "200, 403" }, { method: "POST", path: "/v1/uploads", purpose: "Reserve quota and create multipart grant", permission: "Parent folder editor", idempotency: "Required", responses: "201, 403, 413" }, { method: "POST", path: "/v1/uploads/:id/complete", purpose: "Verify object and queue scan", permission: "Session owner", idempotency: "Parts/checksum bound", responses: "202, 409, 422" }, { method: "POST", path: "/v1/nodes/:id/downloads", purpose: "Issue short-lived download", permission: "Current ACL/share authorization", responses: "201, 403, 423" }, { method: "PATCH", path: "/v1/nodes/:id", purpose: "Rename/move with expected version", permission: "Node editor and destination editor", responses: "200, 409, 412" }, { method: "GET", path: "/v1/changes?cursor=…", purpose: "Ordered tenant sync changes", permission: "Member; results authorization-filtered", responses: "200, 410" }],
  events: [{ name: "UploadFinalized", producer: "Upload API", consumers: "Scanner/type detector", delivery: "Outbox; unique version stage" }, { name: "FileVersionPublished", producer: "Scanner coordinator", consumers: "Preview, search, sync", delivery: "Versioned; consumers dedupe version id" }, { name: "NodeDeleted", producer: "Metadata API", consumers: "Sync, search removal, lifecycle", delivery: "Tombstone retained through cursor window" }],
  failures: [{ name: "Object without metadata", failure: "Upload bytes finish but finalize never runs.", mitigation: "Session/object prefix expiry job deletes unclaimed objects and releases quota." }, { name: "Metadata without object", failure: "Finalize races object-store visibility/failure.", mitigation: "Verify server-side object size/checksum before version transaction; quarantined state never downloads." }, { name: "Quota race", failure: "Concurrent uploads exceed workspace allowance.", mitigation: "Lock quota counter and reserve expected bytes before grants." }, { name: "Unsafe file", failure: "Malware scan fails or times out.", mitigation: "Remain quarantined; bounded retries then explicit blocked/manual state." }, { name: "ACL stale cache", failure: "Revoked user still downloads.", mitigation: "Authorization epoch in cache/token; download grant is short-lived and issued after current check." }, { name: "Folder cycle", failure: "Concurrent moves make a node its descendant.", mitigation: "Lock affected ancestry or use materialized path/version check; reject ambiguous concurrent move." }],
  consistency: { strong: ["Namespace uniqueness", "quota reservation", "current published version", "ACL/share revocation"], eventual: ["Preview", "search index", "device sync delivery", "physical object purge"] },
  concurrency: ["Unique active sibling name constraint", "Quota counter locked per workspace", "Node optimistic version for move/rename", "Upload complete keyed by session/checksum", "Avoid distributed locks; route tenant metadata writes to its database owner"],
  caching: { cache: ["Immutable published versions through CDN", "Thumbnails", "Folder pages briefly with node version"], never: ["Quarantined bytes", "Long-lived ACL decision", "Quota available during reservation"], policy: "Content-addressed/versioned bytes use long TTL. Metadata cache keys include tenant/node version and ACL epoch; revocation bumps epoch." },
  jobs: ["Scan and type-detect", "Thumbnail/preview", "Orphan multipart cleanup", "Search indexing", "Trash retention purge", "Quota reconciliation"],
  security: ["Presigned operations bind bucket key, method, size/checksum, and expiry", "Detect type from bytes; scan/re-encode risky formats", "ACL checks include ancestors and current tenant membership", "Share tokens have high entropy, hashes at rest, expiry, and revocation", "Archive extraction guards path traversal, zip bombs, and file count", "Remote import blocks SSRF and metadata addresses", "Audit shares, downloads, admin actions, and export"],
  observability: { logs: ["Upload session, quota reservation, object verification, scan verdict, and publish transitions", "ACL/share evaluation result with tenant, node, principal type, and policy epoch—never token value", "Move/rename/delete change sequence and optimistic version conflict"], metrics: ["Upload completion, checksum rejection, and orphan-session rate", "Scan queue age, verdict distribution, and preview failure rate", "Reserved-versus-stored quota drift and reconciliation corrections", "Sync cursor lag, change-log retention misses, and download authorization denials"], traces: ["Trace upload from quota reservation through direct-object finalize, scan, publish, and sync event", "Trace shared download through token/ACL resolution and short-lived storage grant"], alerts: ["Quarantined files remain unresolved beyond policy window", "Quota invariant or metadata/object reconciliation drifts", "ACL revocation propagation or sync change feed stalls"] },
  testing: [{ layer: "Unit", coverage: "ACL inheritance, path/name normalization, quota arithmetic, cursor" }, { layer: "Integration", coverage: "Tenant FKs, name race, quota lock, object finalize" }, { layer: "Contract", coverage: "Object store multipart and scanner verdict" }, { layer: "Concurrency", coverage: "Same-name upload, folder move, quota reservation" }, { layer: "Failure", coverage: "Orphan object, scanner crash, stale ACL cache" }, { layer: "End-to-end/load", coverage: "Upload → publish → share → revoke → restore; large multipart metadata pressure" }],
  deployment: [{ stage: "Stage 1", stack: "Metadata API, PostgreSQL, object storage, queue, scanner/preview workers, CDN" }, { stage: "Stage 2", stack: "API replicas, isolated scanner pool, search, Redis, read replica, sync gateway" }, { stage: "Stage 3", stack: "Workspace-sharded metadata cells and region-pinned buckets; global routing directory" }],
  scale: scale("Keep bytes direct-to-storage; scale scan/preview independently; add metadata read replicas and search", "Partition workspaces into regional cells with one metadata writer; replicate immutable bytes under residency policy"),
  diagrams: diagrams("User --> Platform\nExternalRecipient --> Platform\nPlatform --> ObjectStorage\nPlatform --> Scanner\nPlatform --> CDN", "Clients --> MetadataAPI\nMetadataAPI --> PostgreSQL\nMetadataAPI --> ObjectStorage\nPostgreSQL --> Queue\nQueue --> ScanWorker\nQueue --> PreviewWorker\nScanWorker --> ObjectStorage\nCDN --> ObjectStorage", "Client->>MetadataAPI: create upload(size, checksum)\nMetadataAPI->>PostgreSQL: reserve quota + session\nMetadataAPI-->>Client: multipart grants\nClient->>ObjectStorage: upload parts\nClient->>MetadataAPI: complete\nMetadataAPI->>ObjectStorage: verify\nMetadataAPI->>PostgreSQL: quarantined version + outbox\nScanWorker->>PostgreSQL: publish current version"),
};
export default project;
