import Link from "next/link";
import { ArrowRight, GitCompare, Search } from "lucide-react";
import { projects } from "@/content/projects";
import { patterns } from "@/content/patterns";
import { edgeCases } from "@/content/edge-cases";
import { learningPaths } from "@/content/learning-paths";
import { ProjectExplorer } from "@/components/project-explorer";
import { absoluteUrl, site } from "@/lib/site";
import { jsonLd } from "@/lib/seo";

export default function HomePage() {
  const featured = projects.filter((project) => ["ecommerce", "ride-hailing", "payment-platform"].includes(project.slug));
  const structuredData = { "@context": "https://schema.org", "@type": "WebSite", name: site.name, description: site.description, url: absoluteUrl("/"), publisher: { "@type": "Organization", name: site.name }, potentialAction: { "@type": "SearchAction", target: `${absoluteUrl("/search/")}?q={search_term_string}`, "query-input": "required name=search_term_string" } };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd(structuredData) }} />
    <section className="hero"><div className="shell">
      <div className="eyebrow">Production-grade system design · Open source</div>
      <h1>Design systems that survive the real world.</h1>
      <p className="hero-copy">Work from product requirements to the decisions that keep software correct: data models, transactions, races, queues, security, observability, and scale.</p>
      <div className="hero-links"><Link className="button primary" href="#projects">Explore 10 systems <ArrowRight size={16} /></Link><Link className="button" href="/search/"><Search size={16} /> Search the library</Link><Link className="button" href="/compare/"><GitCompare size={16} /> Compare architectures</Link></div>
      <div className="principles"><div className="principle"><strong>Start with the product</strong><span>Actors, workflows, constraints, and non-goals before infrastructure.</span></div><div className="principle"><strong>Correctness before scale</strong><span>Transactions, idempotency, concurrency, and explicit consistency.</span></div><div className="principle"><strong>Evolve with evidence</strong><span>Simple beginnings and workload-driven architecture transitions.</span></div></div>
    </div></section>
    <section className="section start-section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Choose a starting point</div><h2>Three systems. Three kinds of difficulty.</h2><p>Begin with transactional commerce, realtime coordination, or correctness around money.</p></div></div><div className="featured-grid">{featured.map((project, index) => <Link className="featured-project" href={`/projects/${project.slug}/`} key={project.slug}><span className="featured-number">0{index + 1}</span><div><h3>{project.title}</h3><p>{project.summary}</p><span className="text-link">Open case study →</span></div></Link>)}</div></div></section>
    <section className="section" id="projects"><div className="shell"><div className="section-heading"><div><div className="eyebrow">10 flagship systems</div><h2>Project explorer</h2><p>Each case study makes its own domain tradeoffs. Filter by the engineering problem you want to understand.</p></div><Link className="text-link" href="/compare/">Compare two systems →</Link></div><ProjectExplorer projects={projects} /></div></section>
    <section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Inside every case study</div><h2>Learn the decisions between the boxes.</h2></div></div><div className="learn-grid"><div><span>01</span><h3>Model the invariant</h3><p>Identify the rule that must remain true under retries and concurrent requests.</p></div><div><span>02</span><h3>Place the transaction</h3><p>Decide which state changes belong in one commit and which must converge.</p></div><div><span>03</span><h3>Design failure behavior</h3><p>Handle timeouts, duplicate delivery, stale caches, and interrupted workers explicitly.</p></div><div><span>04</span><h3>Draw the security boundary</h3><p>Connect actors and objects to authorization, isolation, and audit requirements.</p></div><div><span>05</span><h3>Observe the workflow</h3><p>Measure the domain signals that reveal stuck, slow, or incorrect work.</p></div><div><span>06</span><h3>Evolve with evidence</h3><p>Add partitions, replicas, and specialized stores only when workload pressure justifies them.</p></div></div></div></section>
    <section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Guided progression</div><h2>Learning paths</h2><p>Move through case studies in an order that builds the relevant mental model.</p></div><Link className="text-link" href="/learn/">View paths →</Link></div><div className="path-grid">{learningPaths.map((path) => <Link href={`/learn/#${path.slug}`} className="path-card" key={path.slug}><h3>{path.title}</h3><p>{path.description}</p><ol className="path-list">{path.projects.map((slug) => <li key={slug}>{projects.find((p) => p.slug === slug)?.title}</li>)}</ol></Link>)}</div></div></section>
    <section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Reusable reasoning</div><h2>Engineering library</h2><p>Patterns explain when not to add complexity. Edge cases begin with the failure you will actually meet.</p></div></div><div className="library-grid"><Link href="/patterns/" className="library-card"><h3>{patterns.length} engineering patterns</h3><p>Minimal examples, selection criteria, and honest tradeoffs.</p></Link><Link href="/edge-cases/" className="library-card"><h3>{edgeCases.length} edge cases</h3><p>Failure mechanism, resulting bug, and concrete mitigation.</p></Link><Link href="/search/?q=idempotency" className="library-card"><h3>Connected search</h3><p>Find a concept across projects, patterns, and edge cases.</p></Link><Link href="/compare/" className="library-card"><h3>Architecture comparison</h3><p>Contrast shared concepts and domain-specific decisions.</p></Link></div></div></section>
    <section className="section"><div className="shell contribution-cta"><div><div className="eyebrow">Built in public</div><h2>Improve the engineering reference.</h2><p>Correct an invariant, add a missed failure, sharpen a diagram, or propose a domain-specific case study.</p></div><div className="hero-links"><a className="button primary" href={site.github}>View on GitHub <ArrowRight size={16} /></a><a className="button" href={`${site.github}/blob/main/CONTRIBUTING.md`}>Contribution guide</a></div></div></section>
  </>;
}
