import type { Project } from "@/lib/types";
import meta from "./metadata.json";
import { diagrams, scale } from "../helpers";

const project: Project = {
  ...meta, difficulty: "Advanced",
  purpose: "Coordinate tenant-scoped projects, tasks, comments, attachments, permissions, activity, and live updates without losing edits or leaking workspace data.",
  assumptions: ["Workspace is the tenant boundary", "Task editing is field-level optimistic collaboration, not a CRDT text editor", "Activity is derived from accepted commands", "Attachments use object storage"],
  nonGoals: ["Source control", "General document editing", "Payroll", "Exactly-once notifications"],
  journeys: [{ name: "Plan work", steps: ["Create project", "Invite members/guests", "Create tasks", "Set assignee/status/dates", "Publish activity", "Fan out live update"] }, { name: "Edit concurrently", steps: ["Client reads task and version", "User changes fields", "PATCH includes expected version", "Server authorizes and conditionally updates", "Conflict returns current representation", "Client merges or retries"] }],
  requirements: { must: ["Workspace and project membership", "Task CRUD and workflow", "Comments and mentions", "Activity feed", "Notifications and search"], should: ["Custom fields", "Saved views", "Dependencies", "Guest access"], future: ["Offline editing", "Automations", "Portfolio planning", "Rich collaborative documents"] },
  nfrs: [{ concern: "Tenant isolation", decision: "All objects carry workspace_id; authorization includes workspace and project membership." }, { concern: "Consistency", decision: "Command writes are strong; activity, search, unread counts, and realtime presence are eventual." }, { concern: "Latency", decision: "Task reads/writes stay interactive; bulk exports are jobs." }, { concern: "Auditability", decision: "Permission, membership, deletion, and automation actions record actor and reason." }, { concern: "Availability", decision: "Realtime and notification outages do not block core task writes." }],
  roles: [{ role: "Workspace owner", access: "Billing, security, members, all projects" }, { role: "Project admin", access: "Project settings and membership" }, { role: "Member", access: "Authorized projects and task actions" }, { role: "Guest", access: "Explicitly shared projects only" }],
  entities: [{ name: "Workspace → Membership", relationship: "Tenant role and account link" }, { name: "Workspace → Project → Task", relationship: "Task cannot cross workspace/project" }, { name: "Task → Comment / Attachment", relationship: "Child content inherits but rechecks task access" }, { name: "Task → TaskEvent", relationship: "Append-only activity fact after command" }, { name: "User → Notification", relationship: "Per-recipient delivery/read projection" }],
  tables: [
    { name: "tasks", purpose: "Mutable work item", columns: ["id UUID PK", "workspace_id UUID FK", "project_id UUID FK", "title TEXT", "status TEXT", "assignee_id UUID NULL", "rank TEXT", "version INT", "deleted_at TIMESTAMPTZ NULL"], constraints: ["FK(workspace_id, project_id) preserves tenant", "version > 0"], indexes: ["(workspace_id, project_id, status, rank)", "(workspace_id, assignee_id, status)"] },
    { name: "project_memberships", purpose: "Project-level access", columns: ["workspace_id UUID", "project_id UUID", "user_id UUID", "role TEXT"], constraints: ["PK(project_id, user_id)", "composite tenant FKs"], indexes: ["(workspace_id, user_id)"] },
    { name: "task_events", purpose: "Activity and integration fact", columns: ["id UUID PK", "workspace_id UUID", "task_id UUID", "actor_id UUID", "kind TEXT", "data JSONB", "created_at TIMESTAMPTZ"], constraints: ["append-only"], indexes: ["(workspace_id, task_id, id)", "(workspace_id, created_at DESC, id DESC)"] },
    { name: "notifications", purpose: "Recipient projection", columns: ["id UUID PK", "workspace_id UUID", "recipient_id UUID", "event_id UUID", "read_at TIMESTAMPTZ NULL"], constraints: ["UNIQUE(recipient_id, event_id)"], indexes: ["(recipient_id, read_at, id DESC)"] },
  ],
  transactions: ["Conditional task update, activity record, and outbox commit together", "Membership removal and share-token revocation are atomic", "Soft-delete tasks for restore/audit; hard-delete expired upload staging and sanitized content after retention"],
  endpoints: [{ method: "GET", path: "/v1/projects/:id/tasks?cursor=…&status=…", purpose: "Stable keyset-paginated task list", permission: "Project member", responses: "200, 403" }, { method: "POST", path: "/v1/projects/:id/tasks", purpose: "Create task", permission: "Project contributor", idempotency: "Client-generated request id recommended", responses: "201, 403, 422" }, { method: "PATCH", path: "/v1/tasks/:id", purpose: "Update fields with If-Match version", permission: "Authorized project member", idempotency: "Conditional version", responses: "200, 409, 412" }, { method: "POST", path: "/v1/tasks/:id/comments", purpose: "Add comment and mentions", permission: "Task viewer with comment right", idempotency: "Client mutation id", responses: "201, 403" }, { method: "GET", path: "/v1/activity?cursor=…", purpose: "Workspace activity by created_at/id cursor", permission: "Filter every event to visible projects", responses: "200, 403" }, { method: "DELETE", path: "/v1/projects/:id/members/:userId", purpose: "Revoke project membership", permission: "Project admin", idempotency: "Delete is idempotent", responses: "204, 403" }],
  events: [{ name: "TaskChanged", producer: "Task module", consumers: "Realtime, search, activity, automation", delivery: "Outbox; task version lets projections discard old events" }, { name: "CommentAdded", producer: "Comment module", consumers: "Mention notifications, search", delivery: "Consumer inbox prevents duplicate notification" }, { name: "MembershipRevoked", producer: "Authorization module", consumers: "Realtime session revocation, audit", delivery: "High priority; reads still reauthorize at source" }],
  failures: [{ name: "Lost update", failure: "Two members overwrite the same task.", mitigation: "Expected version; return 412 with current task for merge." }, { name: "Revoked guest socket", failure: "Guest remains connected after access removal.", mitigation: "Publish revocation and reauthorize subscriptions/events; source reads always enforce access." }, { name: "Duplicate mention", failure: "Comment event is replayed.", mitigation: "Unique recipient/event notification and idempotent email job." }, { name: "Reorder collision", failure: "Many tasks move to the same rank.", mitigation: "Fractional ranks plus asynchronous bounded rebalance with version checks." }, { name: "Search leak", failure: "Index contains content after permission change.", mitigation: "Search filters by current ACL tokens and sensitive result hydration reauthorizes." }, { name: "Upload orphan", failure: "Attachment upload succeeds but task attach fails.", mitigation: "Staging objects expire; finalize only after metadata transaction." }],
  consistency: { strong: ["Membership authorization", "Task command/version", "Project deletion", "attachment ownership"], eventual: ["Search", "activity views", "notifications", "presence/unread counts"] },
  concurrency: ["Optimistic version on task PATCH", "Composite tenant foreign keys prevent cross-workspace references", "Unique client mutation id makes comment retry safe", "Rank rebalance never requires a global distributed lock"],
  caching: { cache: ["Workspace/project configuration by version", "User avatars", "Permission-independent static assets"], never: ["Authorization decision beyond a very short session epoch", "Task version used for writes", "Private search result body"], policy: "Cache-aside configuration using workspace/version keys. Invalidate membership epochs and recheck object access." },
  jobs: ["Search indexing", "Mention/email delivery", "Attachment scan and thumbnail", "Rank rebalance", "Workspace export", "Trash retention purge"],
  security: ["Tenant and project object authorization on every route and socket subscription", "Composite foreign keys prevent cross-tenant attachment", "Signed short-lived upload URLs constrained by key and size", "Sanitize rich text and rendered links", "Audit membership, exports, token creation, and deletions", "Rate-limit invitations, mentions, and public shares", "Revoke sessions/share links when membership changes"],
  observability: { logs: ["Task mutation with workspace/project ids, expected/current version, changed fields, and authorization result", "Membership/share changes and audited export/delete commands", "Realtime/search consumer event version and stale-event decision"], metrics: ["Task optimistic-conflict rate by client/version", "Realtime publish-to-delivery lag and disconnected subscriber count", "Search indexing delay and permission-filter rejection rate", "Notification backlog, mention dedupe, and attachment scan age"], traces: ["Trace task command through PostgreSQL, activity/outbox, realtime, and search projection", "Trace attachment finalize through scan, metadata link, and preview"], alerts: ["Membership revocations fail to reach session gateways", "Search index lag or authorization-filter anomalies", "Hot workspace fan-out causes sustained delivery backlog"] },
  testing: [{ layer: "Unit", coverage: "Permission matrix, state transitions, rank generation, cursor encoding" }, { layer: "Integration", coverage: "Tenant FKs, conditional update, outbox, upload finalize" }, { layer: "Contract", coverage: "Versioned realtime and webhook events" }, { layer: "Concurrency", coverage: "Parallel edits, moves, membership revocation" }, { layer: "Failure", coverage: "Indexer lag, socket disconnect, orphan upload, duplicate event" }, { layer: "End-to-end/load", coverage: "Invite → task → comment → search; hot-project fan-out" }],
  deployment: [{ stage: "Stage 1", stack: "Next.js, modular API, PostgreSQL, object storage, worker, WebSocket gateway" }, { stage: "Stage 2", stack: "API/realtime replicas, Redis presence, search engine, dedicated workers, read replica" }, { stage: "Stage 3", stack: "Workspace-cohort databases and partitioned event/realtime infrastructure" }],
  scale: scale("Split realtime, indexing, and attachment workers; retain one write authority per workspace", "Partition workspaces into cells; route all tenant data and events to its cell, with sanitized aggregate analytics"),
  diagrams: diagrams("Member --> WebApp\nGuest --> WebApp\nWebApp --> Platform\nPlatform --> EmailProvider\nPlatform --> ObjectStorage", "WebApp --> API\nWebApp --> RealtimeGateway\nAPI --> PostgreSQL\nAPI --> ObjectStorage\nPostgreSQL --> Outbox\nOutbox --> Queue\nQueue --> SearchIndexer\nQueue --> NotificationWorker", "ClientA->>API: PATCH task If-Match: 7\nClientB->>API: PATCH task If-Match: 7\nAPI->>PostgreSQL: update where version=7\nPostgreSQL-->>API: A succeeds, version=8\nAPI-->>ClientA: 200 version 8\nAPI->>PostgreSQL: B update where version=7\nPostgreSQL-->>API: 0 rows\nAPI-->>ClientB: 412 + current task"),
};
export default project;
