import type { Project } from "@/lib/types";
import meta from "./metadata.json";
import { diagrams, scale } from "../helpers";

const project: Project = {
  ...meta, difficulty: "Advanced",
  purpose: "Run hotel operations across reservations, room inventory, check-in, housekeeping, folios, and night audit while preserving property-local business dates.",
  assumptions: ["Each property is a tenant boundary", "Room type inventory is sold before a physical room is assigned", "Business date may differ from UTC date", "External channels deliver at-least-once updates"],
  nonGoals: ["Building a public travel marketplace", "Card vaulting", "Door-lock firmware", "Revenue-management optimization"],
  journeys: [
    { name: "Reserve", steps: ["Search rate and room-type availability", "Create short hold", "Collect guarantee token", "Confirm reservation and consume inventory", "Send confirmation"] },
    { name: "Check in", steps: ["Verify identity and reservation", "Assign clean compatible room", "Authorize incidentals", "Create/activate folio", "Set room occupied"] },
    { name: "Night audit", steps: ["Freeze property business date", "Post recurring room charges", "Reconcile unsettled transactions", "Produce audit report", "Advance business date", "Resume writes"] },
  ],
  requirements: { must: ["Rate-plan and room-type inventory", "Reservation lifecycle", "Room assignment and housekeeping", "Folio charges/payments", "Property business date and audit trail"], should: ["Channel-manager integration", "Group blocks", "Room moves", "No-show workflow"], future: ["Revenue management", "Multi-property guest profile", "Digital keys", "Loyalty"] },
  nfrs: [{ concern: "Consistency", decision: "Inventory, room assignment, and folio postings are transactional within a property." }, { concern: "Availability", decision: "A property can continue core front-desk work during nonessential integration outages." }, { concern: "Auditability", decision: "Financial changes are reversals plus new entries, never edits in place." }, { concern: "Timezones", decision: "Store instants in UTC and separately record property timezone and local business date." }, { concern: "Tenant isolation", decision: "Every property-owned row and authorization path carries property_id." }],
  roles: [{ role: "Front desk", access: "Property reservations, rooms, and guest-facing folio actions" }, { role: "Housekeeping", access: "Assigned room status; no folio/payment data" }, { role: "Manager", access: "Property configuration, overrides, and audit" }, { role: "Finance", access: "Folio, settlement, and reports; no room-key actions" }],
  entities: [{ name: "Property → RoomType → Room", relationship: "Type is sellable inventory; room is physical assignment" }, { name: "Reservation → Stay", relationship: "Reservation commitment becomes an operational stay" }, { name: "Stay → RoomAssignment", relationship: "Date-bounded history supports moves" }, { name: "Reservation → Folio → FolioEntry", relationship: "Append-only charges, payments, and reversals" }, { name: "Property → BusinessDate", relationship: "Night audit advances the accounting day" }],
  tables: [
    { name: "reservations", purpose: "Guest booking commitment", columns: ["id UUID PK", "property_id UUID FK", "confirmation_code TEXT", "room_type_id UUID FK", "arrival DATE", "departure DATE", "status TEXT", "version INT"], constraints: ["UNIQUE(property_id, confirmation_code)", "departure > arrival"], indexes: ["(property_id, arrival, status)", "(property_id, guest_id)"] },
    { name: "room_type_inventory", purpose: "Per-night sellable count", columns: ["property_id UUID", "room_type_id UUID", "stay_date DATE", "total INT", "held INT", "sold INT"], constraints: ["PK(property_id, room_type_id, stay_date)", "held + sold <= total"], indexes: ["primary key supports range lookup"] },
    { name: "room_assignments", purpose: "Physical room history", columns: ["id UUID PK", "property_id UUID", "stay_id UUID FK", "room_id UUID FK", "from_at TIMESTAMPTZ", "to_at TIMESTAMPTZ NULL"], constraints: ["exclusion constraint prevents overlapping active room assignment"], indexes: ["(property_id, room_id, from_at)"] },
    { name: "folio_entries", purpose: "Append-only money movements", columns: ["id UUID PK", "property_id UUID", "folio_id UUID FK", "business_date DATE", "kind TEXT", "amount_minor BIGINT", "reverses_id UUID NULL", "source_key TEXT"], constraints: ["UNIQUE(property_id, source_key)", "no update policy"], indexes: ["(property_id, folio_id, id)", "(property_id, business_date)"] },
  ],
  transactions: ["Lock all room-type inventory dates in ascending order before converting hold to sale", "Assign room only if clean and no overlapping assignment", "Night-audit charge source key is unique per stay/date/type", "Reservations are cancelled, folio entries reversed; PII may be anonymized by retention policy"],
  endpoints: [{ method: "GET", path: "/v1/properties/:id/availability?from=&to=", purpose: "Read room-type availability", permission: "Property member or public booking scope", responses: "200, 422" }, { method: "POST", path: "/v1/reservations", purpose: "Hold inventory and confirm booking", permission: "Booking client/front desk", idempotency: "Required", responses: "201, 409, 422" }, { method: "POST", path: "/v1/stays/:id/check-in", purpose: "Assign room and activate stay", permission: "Front desk", idempotency: "Transition id", responses: "200, 409" }, { method: "PATCH", path: "/v1/rooms/:id/housekeeping", purpose: "Update clean/inspected state", permission: "Assigned housekeeping or manager", responses: "200, 409" }, { method: "POST", path: "/v1/folios/:id/entries", purpose: "Post charge, payment, or reversal", permission: "Front desk/finance by entry type", idempotency: "Required source key", responses: "201, 409, 422" }, { method: "POST", path: "/v1/properties/:id/night-audit", purpose: "Advance business date", permission: "Manager with step-up", idempotency: "Business date is the key", responses: "202, 409" }],
  events: [{ name: "ReservationConfirmed", producer: "Reservation module", consumers: "Email, channel sync", delivery: "Outbox and dedupe by reservation/version" }, { name: "RoomStatusChanged", producer: "Housekeeping", consumers: "Front desk projection", delivery: "Versioned last-write projection" }, { name: "BusinessDateAdvanced", producer: "Night audit", consumers: "Reports, integrations", delivery: "Replayable; report output keyed by property/date" }],
  failures: [{ name: "Double booking", failure: "Concurrent channels sell the last room type.", mitigation: "Lock inventory rows for every stay date and enforce held + sold <= total." }, { name: "Duplicate channel message", failure: "Partner resends a reservation.", mitigation: "Unique partner/property external id and return prior result." }, { name: "Dirty room assignment", failure: "Room state changes during check-in.", mitigation: "Lock room and validate clean state inside assignment transaction." }, { name: "Night audit crash", failure: "Audit stops after some charges.", mitigation: "Idempotent source keys and checkpointed phases allow resume without duplicates." }, { name: "DST boundary", failure: "Local time repeats or skips.", mitigation: "Business date is explicit; convert instants with IANA timezone and never derive audit date from server locale." }, { name: "Payment terminal offline", failure: "Authorization status is unknown.", mitigation: "Record pending external operation; reconcile rather than posting an assumed payment." }],
  consistency: { strong: ["Nightly room-type inventory", "Physical room assignment", "Folio append", "Business-date advance"], eventual: ["Channel availability push", "Confirmation email", "Portfolio analytics", "guest-profile merge"] },
  concurrency: ["Lock inventory rows in stable date order", "PostgreSQL exclusion constraint prevents overlapping room assignment", "Optimistic version protects reservation edits", "Unique source keys make night-audit postings idempotent"],
  caching: { cache: ["Property configuration by version", "Room descriptions and media", "Public rate display for short TTL"], never: ["Check-in room eligibility", "Authoritative inventory during confirm", "Folio balance used for checkout"], policy: "Tenant-keyed cache entries; invalidate configuration changes. Booking and operations re-read PostgreSQL." },
  jobs: ["Expire holds", "Send confirmations", "Push channel availability", "Run resumable night audit", "Reconcile terminals", "Anonymize guest PII after retention"],
  security: ["property_id derived from membership, never trusted from body", "Role and object checks for rooms, reservations, folios", "Step-up and dual-control policy for sensitive refunds/audit override", "Tokenized payment methods and segmented terminal integration", "Immutable audit of guest-record access and financial changes", "Rate-limit public availability and confirmation-code lookup", "Mask identity fields from housekeeping views"],
  observability: { logs: ["Reservation, room assignment, folio reversal, and business-date transition with property and actor ids", "Channel message external id, dedupe result, and inventory version", "Night-audit phase checkpoint and idempotent posting outcome"], metrics: ["Room-type inventory conflicts and oversell prevention by property/date", "Channel availability sync lag and rejection rate", "Night-audit phase duration, restart count, and properties not advanced", "Dirty-room wait time and unresolved folio balance count"], traces: ["Trace reservation from channel/public API through nightly inventory locks", "Trace check-in across room eligibility, incidental authorization, and folio activation"], alerts: ["Property inventory invariant violation", "Night audit misses property cutover window", "Channel sync lag risks selling stale availability"] },
  testing: [{ layer: "Unit", coverage: "Stay-date ranges, DST cases, folio reversal, state machines" }, { layer: "Integration", coverage: "Inventory locks, exclusion constraints, tenant policies, audit idempotency" }, { layer: "Contract", coverage: "Channel and terminal message fixtures" }, { layer: "Concurrency", coverage: "Last-room channel race and simultaneous room assignment" }, { layer: "Failure", coverage: "Audit phase crash, offline terminal, late cancellation" }, { layer: "End-to-end", coverage: "Reserve → check-in → move → charges → checkout → night audit" }],
  deployment: [{ stage: "Stage 1", stack: "Modular web app/API, PostgreSQL, queue worker, object storage" }, { stage: "Stage 2", stack: "API replicas, integration workers, read replica for portfolio reports, Redis config cache" }, { stage: "Stage 3", stack: "Property cohorts with independent operational databases; centralized read-only analytics" }],
  scale: scale("Scale channel and reporting workers separately; route all property writes to one primary owner", "Partition by property cohort/region; keep night audit and inventory single-writer per property; replicate sanitized events to analytics"),
  diagrams: diagrams("Guest --> PMS\nFrontDesk --> PMS\nHousekeeping --> PMS\nPMS --> PaymentTerminal\nPMS --> ChannelManager", "WebApp --> API\nAPI --> PostgreSQL\nAPI --> Queue\nQueue --> IntegrationWorker\nQueue --> AuditWorker\nIntegrationWorker --> Channels", "Guest->>API: reservation request\nAPI->>PostgreSQL: lock date inventory\nAPI->>PaymentTerminal: guarantee token\nAPI->>PostgreSQL: sold++, reservation + outbox\nAPI-->>Guest: confirmation\nAPI-->>ChannelManager: availability changed"),
};
export default project;
