import type { Pattern } from "@/lib/types";

export const patterns: Pattern[] = [
  { slug: "idempotency-keys", title: "Idempotency Keys", summary: "Make retried commands return one durable outcome.", problem: "Networks lose responses, so a caller cannot know whether a mutation happened.", useWhen: ["Creating payments, orders, bookings, or jobs", "A client or broker will retry"], avoidWhen: ["Pure reads", "The operation is naturally idempotent and cheap"], example: "Store (actor_id, key, request_hash, status, response). Reject a reused key with a different hash; replay the stored response.", tradeoffs: ["Needs retention and concurrent in-progress behavior", "Scope keys to an authenticated actor"] },
  { slug: "outbox-pattern", title: "Outbox Pattern", summary: "Commit a domain change and a message-to-publish together.", problem: "A database commit and queue publish cannot usually be one atomic action.", useWhen: ["A committed write must eventually trigger consumers", "At-least-once delivery is acceptable"], avoidWhen: ["A synchronous call is sufficient", "The database itself is not authoritative"], example: "In one transaction update the order and insert outbox(event_id, type, payload). A relay publishes and marks the row sent.", tradeoffs: ["Duplicates remain possible", "Relay lag and table cleanup need monitoring"] },
  { slug: "saga-pattern", title: "Saga Pattern", summary: "Coordinate a long workflow through compensatable local transactions.", problem: "A business workflow spans systems that cannot share one transaction.", useWhen: ["Steps have explicit compensations", "Pending states are acceptable"], avoidWhen: ["One database transaction suffices", "Actions cannot be compensated and ambiguity is unacceptable"], example: "Reserve stock → authorize payment → request fulfillment. On rejection, void authorization and release reservation.", tradeoffs: ["Compensation is not time travel", "Requires durable state, idempotent steps, and operations tooling"] },
  { slug: "optimistic-locking", title: "Optimistic Locking", summary: "Reject stale writes with a version precondition.", problem: "Concurrent editors can silently overwrite one another.", useWhen: ["Conflicts are uncommon", "Users can merge or retry"], avoidWhen: ["A hot counter has constant contention", "The invariant spans many changing rows"], example: "UPDATE tasks SET ..., version=8 WHERE id=? AND version=7; zero rows means 412 Precondition Failed.", tradeoffs: ["Clients need conflict UX", "Retries must recompute from fresh state"] },
  { slug: "pessimistic-locking", title: "Pessimistic Locking", summary: "Serialize a short critical section with database row locks.", problem: "A scarce resource must be checked and changed without interference.", useWhen: ["Inventory or refund limit contention is bounded", "All writers share the database owner"], avoidWhen: ["Long external calls occur in the transaction", "Rows are locked in inconsistent order"], example: "SELECT inventory ... FOR UPDATE; verify available; update reserved; commit before calling external services.", tradeoffs: ["Can deadlock or reduce throughput", "Lock order and timeout policy matter"] },
  { slug: "retry-with-backoff", title: "Retry with Backoff", summary: "Retry transient work without amplifying an outage.", problem: "Immediate synchronized retries overload an already failing dependency.", useWhen: ["Failure is plausibly transient", "Operation is idempotent or deduplicated"], avoidWhen: ["Validation/auth errors", "Deadline is already exhausted"], example: "Exponential delay with full jitter, attempt cap, per-operation deadline, and a dead-letter/manual state.", tradeoffs: ["Increases completion latency", "Unbounded retry hides poison messages"] },
  { slug: "circuit-breaker", title: "Circuit Breaker", summary: "Stop spending resources on a dependency that is persistently failing.", problem: "Timeouts cascade through callers and exhaust pools.", useWhen: ["Remote calls fail independently", "A fallback or explicit unavailable response exists"], avoidWhen: ["Local database constraints", "A breaker would mask correctness-required work"], example: "Open after a rolling failure threshold, reject briefly, then allow limited half-open probes.", tradeoffs: ["Thresholds can flap", "It complements—not replaces—timeouts and bulkheads"] },
  { slug: "rate-limiting", title: "Rate Limiting", summary: "Bound resource use and abuse across meaningful identities.", problem: "One caller or attack can monopolize finite capacity.", useWhen: ["Public APIs, login, messaging, expensive commands", "Fairness and abuse controls matter"], avoidWhen: ["As the only authorization or cost control", "A single global limit penalizes all tenants"], example: "Token bucket by API key plus IP/risk dimension; return 429 with retry guidance.", tradeoffs: ["Distributed counters may be approximate", "Limits need per-route cost and trusted identity"] },
  { slug: "cache-aside", title: "Cache Aside", summary: "Read through an application-managed cache while keeping a durable source of truth.", problem: "Repeated derived or database reads are expensive or slow.", useWhen: ["Staleness is bounded and acceptable", "Misses can safely fall back"], avoidWhen: ["Money or reservation decisions", "Invalidation cannot be made safe"], example: "Read cache; on miss read DB and set TTL. On write commit DB then invalidate versioned key.", tradeoffs: ["Stale reads and stampedes", "Needs TTL, invalidation, and negative-cache policy"] },
  { slug: "cqrs", title: "CQRS", summary: "Use separate command and read models when their needs truly diverge.", problem: "A normalized write model may not efficiently serve complex projections.", useWhen: ["Many read shapes lag safely", "Projection rebuilding is understood"], avoidWhen: ["Simple CRUD", "Teams cannot operate asynchronous projections"], example: "Commands write orders; events update customer timeline and operations queue projections.", tradeoffs: ["Eventual consistency", "More schemas, versioning, repair, and observability"] },
  { slug: "event-sourcing", title: "Event Sourcing", summary: "Persist domain events as the primary state history.", problem: "Some domains need complete temporal reconstruction and alternative projections.", useWhen: ["Event semantics are stable and audit is central", "Team can evolve/replay schemas"], avoidWhen: ["Ordinary audit logging is enough", "Deletion/privacy requirements conflict with immutable payloads"], example: "Append AccountCredited v3 with expected stream version; fold events to derive balance.", tradeoffs: ["Hard migrations and debugging", "Snapshots, upcasters, privacy design, and projection repair are mandatory"] },
  { slug: "webhooks", title: "Webhooks", summary: "Deliver signed at-least-once events between independently operated systems.", problem: "A consumer needs changes without polling continuously.", useWhen: ["Consumers expose stable HTTPS endpoints", "Delivery can be asynchronous"], avoidWhen: ["Immediate command response is required", "Sensitive payload cannot be minimized"], example: "Sign timestamp + raw body; unique event id; retry 2xx failures with jitter; expose replay UI.", tradeoffs: ["Duplicates, reordering, and endpoint outages", "Secret rotation and SSRF-safe registration matter"] },
  { slug: "distributed-locks", title: "Distributed Locks", summary: "Coordinate across owners only when database constraints or partition ownership cannot.", problem: "Multiple processes sometimes need a time-bounded lease over an external resource.", useWhen: ["A real cross-system singleton remains after redesign", "Fencing tokens protect the resource"], avoidWhen: ["A unique constraint, row lock, or single partition owner works", "Correctness relies only on lease expiry"], example: "Acquire monotonic fencing token; resource rejects operations with an older token even if a paused holder resumes.", tradeoffs: ["Leases expire during pauses", "Without fencing, mutual exclusion can be illusory"] },
  { slug: "pagination", title: "Pagination", summary: "Traverse changing datasets with stable keyset cursors.", problem: "Offset pages become slow and duplicate/skip rows during concurrent writes.", useWhen: ["Large ordered lists", "A deterministic compound sort exists"], avoidWhen: ["Tiny fixed datasets", "Users require random page numbers more than consistency"], example: "ORDER BY created_at DESC, id DESC; cursor encodes both; next query uses tuple < cursor.", tradeoffs: ["No cheap arbitrary page jump", "Filters and ordering must be bound into cursor"] },
  { slug: "multi-tenancy", title: "Multi-tenancy", summary: "Make tenant ownership explicit in identity, schema, authorization, caches, and operations.", problem: "Shared infrastructure can leak one customer's data to another.", useWhen: ["A SaaS serves isolated organizations", "Operations must reason about tenant placement"], avoidWhen: ["The domain is consumer-owned rather than tenant-owned", "A label is being added without isolation semantics"], example: "Include workspace_id in tables, composite foreign keys, queries, jobs, object keys, cache keys, logs, and quotas.", tradeoffs: ["Shared, schema-per-tenant, and database-per-tenant have different cost/isolation", "Migration and noisy-neighbor controls matter"] },
  { slug: "background-jobs", title: "Background Jobs", summary: "Run durable, retryable work outside an interactive request.", problem: "Slow or failure-prone work should not hold a user request open.", useWhen: ["Email, media, reconciliation, exports", "A pending state is acceptable"], avoidWhen: ["Caller needs the result to proceed", "Fire-and-forget memory tasks"], example: "Persist job/outbox, acknowledge only after durable enqueue, lease work, make handler idempotent, record terminal failure.", tradeoffs: ["At-least-once execution", "Needs queue-age SLO, backpressure, replay, and cancellation"] },
  { slug: "audit-logs", title: "Audit Logs", summary: "Record who did what, to which object, when, and why.", problem: "Sensitive changes need investigation and accountability beyond application logs.", useWhen: ["Permissions, finance, support access, exports", "Compliance or customer trust needs evidence"], avoidWhen: ["As a substitute for domain history", "Recording secrets or excessive personal data"], example: "Append actor, tenant, action, target, reason, request id, and safe before/after fields to access-controlled storage.", tradeoffs: ["Tamper evidence, retention, and access controls", "Audit data itself is sensitive"] },
];

export const patternBySlug = new Map(patterns.map((pattern) => [pattern.slug, pattern]));
